import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import { agents } from '@/mocks/data';
import {
  Heart, Brain, BarChart3, MessageSquare, Users, GraduationCap,
  Server, Database, Shield, Workflow, Layers, Table2
} from 'lucide-react';

const iconMap: Record<string, React.ElementType> = {
  Heart, Brain, BarChart3, MessageSquare, Users, GraduationCap,
};

const typeColor: Record<string, string> = {
  analyzer: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
  synthesis: 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200',
  copilot: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200',
};

const mcpServers = [
  {
    name: 'HR Data Gateway',
    endpoint: '/mcp/hr-data',
    description: 'Exposes employee records, absence history, and org-chart data to analyzer agents.',
    tools: ['get_employee_profile', 'list_absences', 'get_org_tree'],
    status: 'active' as const,
  },
  {
    name: 'Delivery Metrics Server',
    endpoint: '/mcp/delivery',
    description: 'Provides sprint velocity, PR review stats, and workload metrics from Jira & GitHub.',
    tools: ['get_sprint_summary', 'get_pr_metrics', 'get_meeting_load'],
    status: 'active' as const,
  },
  {
    name: 'Learning & Skills Server',
    endpoint: '/mcp/learning',
    description: 'Serves training records, certification status, and IDP progress data.',
    tools: ['get_training_records', 'get_idp_goals', 'get_skill_assessments'],
    status: 'active' as const,
  },
  {
    name: 'Wellbeing Signals Server',
    endpoint: '/mcp/wellbeing',
    description: 'Aggregates psychological safety surveys, pulse check results, and sentiment data.',
    tools: ['get_pulse_results', 'get_safety_scores', 'get_sentiment_trends'],
    status: 'planned' as const,
  },
];

const dbTables = [
  {
    name: 'employees',
    description: 'Core employee profile data with computed risk and performance scores.',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'name', type: 'text', pk: false },
      { name: 'role', type: 'text', pk: false },
      { name: 'department', type: 'text', pk: false },
      { name: 'tenure', type: 'text', pk: false },
      { name: 'wellbeing_score', type: 'integer', pk: false },
      { name: 'skills_score', type: 'integer', pk: false },
      { name: 'motivation_score', type: 'integer', pk: false },
      { name: 'delivery_score', type: 'integer', pk: false },
      { name: 'churn_risk', type: 'integer', pk: false },
      { name: 'status', type: 'enum(green,yellow,red)', pk: false },
    ],
  },
  {
    name: 'signals',
    description: 'Real-time alerts and notifications generated by analyzer agents.',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'title', type: 'text', pk: false },
      { name: 'severity', type: 'enum(critical,warning,info,positive)', pk: false },
      { name: 'category', type: 'enum(wellbeing,skills,motivation,churn,delivery)', pk: false },
      { name: 'employee_id', type: 'uuid → employees', pk: false },
      { name: 'timestamp', type: 'timestamptz', pk: false },
      { name: 'is_read', type: 'boolean', pk: false },
    ],
  },
  {
    name: 'kpis',
    description: 'Key performance indicators with trend tracking and sub-KPI breakdowns.',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'name', type: 'text', pk: false },
      { name: 'value', type: 'numeric', pk: false },
      { name: 'previous_value', type: 'numeric', pk: false },
      { name: 'status', type: 'enum(green,yellow,red)', pk: false },
      { name: 'trend', type: 'numeric', pk: false },
      { name: 'category', type: 'enum(signal_categories)', pk: false },
    ],
  },
  {
    name: 'one_on_one_meetings',
    description: 'Scheduled and completed 1:1 meetings with topics and follow-up actions.',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'employee_id', type: 'uuid → employees', pk: false },
      { name: 'date', type: 'timestamptz', pk: false },
      { name: 'duration', type: 'integer', pk: false },
      { name: 'status', type: 'enum(scheduled,completed,cancelled)', pk: false },
      { name: 'notes', type: 'text', pk: false },
    ],
  },
  {
    name: 'idp_goals',
    description: 'Individual development plan goals linked to employees and skill areas.',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'employee_id', type: 'uuid → employees', pk: false },
      { name: 'title', type: 'text', pk: false },
      { name: 'progress', type: 'integer', pk: false },
      { name: 'target_date', type: 'date', pk: false },
      { name: 'status', type: 'enum(on-track,at-risk,behind,completed)', pk: false },
      { name: 'skill_area', type: 'text', pk: false },
    ],
  },
  {
    name: 'user_roles',
    description: 'Role assignments for access control (team-lead, team-member, admin).',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'user_id', type: 'uuid → auth.users', pk: false },
      { name: 'role', type: 'enum(team-lead,team-member,admin)', pk: false },
    ],
  },
];

const ArchitecturePage = () => {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">System Architecture</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Agents, MCP servers, and database schema powering LogIQ
        </p>
      </div>

      <Tabs defaultValue="agents" className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="agents" className="flex items-center gap-2">
            <Workflow className="w-4 h-4" />
            Agents
          </TabsTrigger>
          <TabsTrigger value="mcp" className="flex items-center gap-2">
            <Server className="w-4 h-4" />
            MCP Servers
          </TabsTrigger>
          <TabsTrigger value="schema" className="flex items-center gap-2">
            <Database className="w-4 h-4" />
            DB Schema
          </TabsTrigger>
        </TabsList>

        {/* ── AGENTS TAB ── */}
        <TabsContent value="agents" className="space-y-4 mt-4">
          {/* Architecture diagram */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-lg flex items-center gap-2">
                <Layers className="w-5 h-5 text-primary" />
                Agent Pipeline
              </CardTitle>
              <CardDescription>How data flows from sources through agents to user interfaces</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center gap-3 py-4">
                {/* Sources */}
                <div className="flex gap-3 flex-wrap justify-center">
                  {['HR Systems', 'Jira / GitHub', 'Surveys', 'LMS'].map(s => (
                    <div key={s} className="px-3 py-1.5 rounded-md border border-border bg-muted text-xs font-medium text-muted-foreground">
                      {s}
                    </div>
                  ))}
                </div>
                <div className="text-muted-foreground text-lg">↓</div>
                {/* MCP Layer */}
                <div className="px-4 py-2 rounded-lg border-2 border-dashed border-primary/30 bg-primary/5 text-sm font-semibold text-primary">
                  MCP Servers (data ingestion)
                </div>
                <div className="text-muted-foreground text-lg">↓</div>
                {/* Analyzers */}
                <div className="flex gap-3 flex-wrap justify-center">
                  {agents.filter(a => a.type === 'analyzer').map(a => (
                    <div key={a.id} className="px-3 py-1.5 rounded-md bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 text-xs font-medium">
                      {a.name}
                    </div>
                  ))}
                </div>
                <div className="text-muted-foreground text-lg">↓</div>
                {/* Synthesis */}
                <div className="flex gap-3 flex-wrap justify-center">
                  {agents.filter(a => a.type === 'synthesis').map(a => (
                    <div key={a.id} className="px-3 py-1.5 rounded-md bg-amber-100 dark:bg-amber-900 text-amber-800 dark:text-amber-200 text-xs font-medium">
                      {a.name}
                    </div>
                  ))}
                </div>
                <div className="text-muted-foreground text-lg">↓</div>
                {/* Copilots */}
                <div className="flex gap-3 flex-wrap justify-center">
                  {agents.filter(a => a.type === 'copilot').map(a => (
                    <div key={a.id} className="px-3 py-1.5 rounded-md bg-emerald-100 dark:bg-emerald-900 text-emerald-800 dark:text-emerald-200 text-xs font-medium">
                      {a.name}
                    </div>
                  ))}
                </div>
                <div className="text-muted-foreground text-lg">↓</div>
                {/* UI */}
                <div className="flex gap-3 flex-wrap justify-center">
                  {['Lead Dashboard', 'Member Dashboard', 'Signals', '1:1 Planner'].map(s => (
                    <div key={s} className="px-3 py-1.5 rounded-md border border-border bg-card text-xs font-medium text-foreground shadow-sm">
                      {s}
                    </div>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Agent cards */}
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {agents.map(agent => {
              const Icon = iconMap[agent.icon] || Brain;
              return (
                <Card key={agent.id} className="relative overflow-hidden">
                  <CardHeader className="pb-2">
                    <div className="flex items-start justify-between">
                      <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                        <Icon className="w-5 h-5 text-primary" />
                      </div>
                      <Badge className={typeColor[agent.type]}>{agent.type}</Badge>
                    </div>
                    <CardTitle className="text-base mt-2">{agent.name}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">{agent.description}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </TabsContent>

        {/* ── MCP SERVERS TAB ── */}
        <TabsContent value="mcp" className="space-y-4 mt-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-lg flex items-center gap-2">
                <Shield className="w-5 h-5 text-primary" />
                MCP Server Overview
              </CardTitle>
              <CardDescription>
                Model Context Protocol servers expose structured tools that agents call to retrieve external data.
              </CardDescription>
            </CardHeader>
          </Card>

          <Accordion type="multiple" className="space-y-2">
            {mcpServers.map((server, i) => (
              <AccordionItem key={i} value={`mcp-${i}`} className="border rounded-lg px-4">
                <AccordionTrigger className="hover:no-underline">
                  <div className="flex items-center gap-3">
                    <Server className="w-4 h-4 text-primary flex-shrink-0" />
                    <span className="font-semibold text-sm">{server.name}</span>
                    <Badge variant={server.status === 'active' ? 'default' : 'secondary'} className="ml-2 text-xs">
                      {server.status}
                    </Badge>
                  </div>
                </AccordionTrigger>
                <AccordionContent className="space-y-3 pb-4">
                  <p className="text-sm text-muted-foreground">{server.description}</p>
                  <div>
                    <p className="text-xs font-semibold text-foreground mb-1.5">Endpoint</p>
                    <code className="text-xs bg-muted px-2 py-1 rounded font-mono text-foreground">{server.endpoint}</code>
                  </div>
                  <div>
                    <p className="text-xs font-semibold text-foreground mb-1.5">Tools</p>
                    <div className="flex flex-wrap gap-1.5">
                      {server.tools.map(tool => (
                        <code key={tool} className="text-xs bg-muted px-2 py-0.5 rounded font-mono text-muted-foreground">
                          {tool}
                        </code>
                      ))}
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </TabsContent>

        {/* ── DB SCHEMA TAB ── */}
        <TabsContent value="schema" className="space-y-4 mt-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-lg flex items-center gap-2">
                <Table2 className="w-5 h-5 text-primary" />
                Database Schema
              </CardTitle>
              <CardDescription>
                PostgreSQL tables powering the LogIQ data model. Foreign keys denoted with →.
              </CardDescription>
            </CardHeader>
          </Card>

          <Accordion type="multiple" className="space-y-2">
            {dbTables.map((table, i) => (
              <AccordionItem key={i} value={`table-${i}`} className="border rounded-lg px-4">
                <AccordionTrigger className="hover:no-underline">
                  <div className="flex items-center gap-3">
                    <Database className="w-4 h-4 text-primary flex-shrink-0" />
                    <code className="font-semibold text-sm font-mono">{table.name}</code>
                    <span className="text-xs text-muted-foreground ml-2">{table.columns.length} columns</span>
                  </div>
                </AccordionTrigger>
                <AccordionContent className="pb-4">
                  <p className="text-sm text-muted-foreground mb-3">{table.description}</p>
                  <div className="rounded-lg border overflow-hidden">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="bg-muted/50">
                          <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">Column</th>
                          <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">Type</th>
                          <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">Key</th>
                        </tr>
                      </thead>
                      <tbody>
                        {table.columns.map(col => (
                          <tr key={col.name} className="border-t border-border">
                            <td className="px-3 py-1.5 font-mono text-xs text-foreground">{col.name}</td>
                            <td className="px-3 py-1.5 font-mono text-xs text-muted-foreground">{col.type}</td>
                            <td className="px-3 py-1.5">{col.pk && <Badge variant="outline" className="text-[10px] px-1.5">PK</Badge>}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default ArchitecturePage;
